version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rider
      - SECRET_KEY=${SECRET_KEY}  # Change this in production
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - uv-cache:/root/.cache/uv  # Cache uv packages
    networks:
      - ride-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ride
    ports:
      - "5430:5430"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ride-network
    restart: unless-stopped

volumes:
  postgres_data:
  uv-cache:  # Volume for uv package cache

networks:
  ride-network:
    driver: bridge 